-- Run this in the Supabase SQL Editor to create the enquiries table

CREATE TABLE IF NOT EXISTS public.customer_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    query TEXT NOT NULL,
    status TEXT DEFAULT 'unread' NOT NULL, -- 'unread' or 'read'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and add basic policies (if RLS is enabled on your DB)
ALTER TABLE public.customer_enquiries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts to customer_enquiries" 
ON public.customer_enquiries FOR INSERT 
TO public 
WITH CHECK (true);

CREATE POLICY "Allow service role all on customer_enquiries" 
ON public.customer_enquiries FOR ALL 
TO service_role 
USING (true);
